using Dapper;
using Npgsql;

namespace TestTask.Api.Data;

public sealed class DatabaseInitializer(NpgsqlDataSource dataSource)
{
    private const string CreateElementsTableSql = """
        CREATE TABLE IF NOT EXISTS elements
        (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            attribute_value text NULL,
            html text NOT NULL
        );
        """;

    public async Task InitializeAsync(CancellationToken cancellationToken)
    {
        await using var connection = await dataSource.OpenConnectionAsync(cancellationToken);

        await connection.ExecuteAsync(new CommandDefinition(
            CreateElementsTableSql,
            cancellationToken: cancellationToken));
    }
}
